OrangeManagementSystemMain/OrangeManagement/Models/DbHelper.cs
//-----------------------------------------------【Function Indroduction】----------------------------------------------
//	  DBHelper：  database connected class
//    Language：  C#
//    IDE：VS2013
//    2015.12.04  Created by RaymondMG  
//---------------------------------------------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Migrations;

namespace OrangeManagement.Models
{
    public class DbHelper : DbContext
    {
        public DbHelper()
            : base("strConn")
        {
            //自动创建表，如果Entity有改到就更新到表结构
            Database.SetInitializer(new MigrateDatabaseToLatestVersion<DbHelper, ReportingDbMigrationsConfiguration>());
        }
        
        
        //校区管理表
        public DbSet<CampusModel> CampusModule { get; set; }


    }
    internal sealed class ReportingDbMigrationsConfiguration : DbMigrationsConfiguration<DbHelper>
    {
        public ReportingDbMigrationsConfiguration()
        {
            AutomaticMigrationsEnabled = true;//所有model修改直接更新DB
            AutomaticMigrationDataLossAllowed = true;
        }
    }
}

OrangeManagementSystemMain/OrangeManagement/Models/OrangeManagementModel.cs
//-----------------------------------------------【Function Indroduction】----------------------------------------------
//	  DBHelper：  database connected class
//    Language：  C#
//    IDE：VS2013
//    2015.10.16  Created by RaymondMG  
//---------------------------------------------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrangeManagement.Models
{
    /// <summary>
    /// 校区管理
    /// </summary>
    [Table("T_CampusModel", Schema = "dbo")]//关联数据表
    public class CampusModel
    {
        [Key]
        public int CampusId { get; set; }

        //校区名
        [Required]
        [Display(Name = "校区名称")]
        public string CampusName { get; set; }


        //校区编号
        [Required]
        [Display(Name = "校区编号")]
        public string CampusNumber { get; set; }

        //校区简介
        [Required]
        [Display(Name = "校区简介")]
        public string CampusDescribe { get; set; }

        //校区地址
        [Required]
        [Display(Name = "校区地址")]
        public string CampusAddress { get; set; }
    }

}

OrangeManagementSystemMain/OrangeManagement/Controllers/BackGroundController.cs
using System.Data;
using System.Linq;
using System.Web.Mvc;
using OrangeManagement.Models;

namespace OrangeManagement.Controllers
{
    /// <summary>
    /// 后台管理控制器
    /// </summary>
    public class BackGroundController : Controller
    {
        readonly DbHelper _db = new DbHelper();

        //新建校区
        [HttpPost]
        public ActionResult CreateNewCampus(CampusModel model)
        {

            if (!ModelState.IsValid) return View("CampusManagement");

            var newCampus = new CampusModel
            {
                CampusAddress = model.CampusAddress,
                CampusDescribe = model.CampusDescribe,
                CampusName = model.CampusName,
                CampusNumber = model.CampusNumber
            };

            _db.CampusModule.Add(newCampus);
            _db.SaveChanges();
            return View("CampusManagement");
        }

        //编辑校区信息
        [HttpPost]
        public ActionResult EditCampus(CampusModel model)
        {
            if (!ModelState.IsValid) return View("CampusManagement");

            var nowEditModel = _db.CampusModule.FirstOrDefault(it => it.CampusId == model.CampusId);
            
             if (nowEditModel != null)
             {
                 nowEditModel.CampusAddress = model.CampusAddress;
                 nowEditModel.CampusDescribe = model.CampusDescribe;
                 nowEditModel.CampusName = model.CampusName;
                 nowEditModel.CampusNumber = model.CampusNumber;
            };
     
            _db.SaveChanges();
            return View("CampusManagement");
        }
        
        
        //删除校区信息
        [HttpPost]
        public ActionResult DeleteCampus(System.Int32 deleteId)
        {
            _db.Entry(_db.CampusModule.FirstOrDefault(it => it.CampusId == deleteId)).State = EntityState.Deleted;
            _db.SaveChanges();
            return View("CampusManagement");
        }
        /// <summary>
        /// 登陆界面
        /// </summary>
        /// <returns></returns>
        public ActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// 校区管理
        /// </summary>
        /// <returns></returns>
        public ActionResult CampusManagement()
        {
            return View();
        }

        /// <summary>
        /// 校区管理首页
        /// </summary>
        /// <returns></returns>
        public ActionResult CampusInfo()
        {
            return View();
        }
   
        /// <summary>
        /// 后台管理首页
        /// </summary>
        /// <returns></returns>
        public ActionResult BackGroundHome()
        {
            return View();
        }

    }
}

OrangeManagementSystemMain/OrangeManagement/Controllers/EditCampusController.cs
using System.Web.Mvc;

namespace OrangeManagement.Controllers
{
    public class EditCampusController : Controller
    {
    }
}

OrangeManagementSystemMain/OrangeManagement/Views/BackGround/BackGroundHome.cshtml
@{
    ViewBag.Title = "BackGroundHome";
    Layout = "~/Views/Shared/_Layout.cshtml";

    if (Session["LoginOrNot"] == null)
    {
        Response.Redirect("Login");
    }
}

@*设置信息模态框*@
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>设置</h3>
            </div>
            <div class="modal-body">
                <p>当前模块信息设置</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
                <a href="#" class="btn btn-primary" data-dismiss="modal">保存</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well">
                <h2>
                    <i class="glyphicon glyphicon-info-sign"></i> 最新通知
                </h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default">
                        <i class="glyphicon glyphicon-cog"></i>
                    </a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>
                </div>
            </div>
            <div class="box-content row">
                <div class="col-lg-7 col-md-12">
                    <h1>
                        管理信息系统开发计划 <br>
                        <small>当前开发内容：页面框架设计与完善</small>
                    </h1>
                    <p>
                        页面框架设计：左右排版样式
                    </p>

                    <p>
                        <b>
                            样式颜色基调：淡蓝色
                        </b>
                    </p>

                    <p class="center-block download-buttons">
                        <a href="#" class="btn btn-primary btn-lg">
                            <i class="glyphicon glyphicon-chevron-left glyphicon-white"></i> 获取设计样式图1
                        </a>
                        <a href="#" class="btn btn-default btn-lg">
                            <i class="glyphicon glyphicon-download-alt"></i> 获取设计样式图2
                        </a>
                    </p>
                </div>
             
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-calendar"></i> 课程表</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default">
                        <i class="glyphicon glyphicon-cog"></i>
                    </a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>
                </div>
            </div>
            <div class="box-content">


                <div id="calendar"></div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

OrangeManagementSystemMain/OrangeManagement/Views/BackGround/CampusInfo.cshtml
@{
    ViewBag.Title = "CampusInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string campusName = null;
    if (Request.QueryString["cname"] != null)
    {
        campusName = Request.QueryString["cname"];
    }
}

<h2>@campusName</h2>

OrangeManagementSystemMain/OrangeManagement/Views/BackGround/CampusManagement.cshtml
@using OrangeManagement.Models
@model OrangeManagement.Models.CampusModel
@{
    ViewBag.Title = "校区管理";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var db = new DbHelper();
    var campus = db.CampusModule.ToArray();
    
    var count = 1;
    var campusInfos = campus.Cast<CampusModel>().ToDictionary(item => count++);

}
@*设置信息模态框*@
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>设置</h3>
            </div>
            <div class="modal-body">
                <p>当前模块信息设置</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
                <a class="btn btn-primary" data-dismiss="modal">保存</a>
            </div>
        </div>
    </div>
</div>

@*删除校区*@
<div class="modal fade" id="deleteCapmus" tabindex="-1" role="dialog" aria-labelledby="deleteCapmusLabel"
     aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm("DeleteCampus", "BackGround"))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <fieldset>
                    <form role="form">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">×</button>
                            <h3>删除校区</h3>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <p id="info"></p>
                                <input id="infoid" class="control-label" hidden />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
                            <button type="submit" class="btn btn-primary">删除</button>
                        </div>
                    </form>
                </fieldset>
            }
        </div>
    </div>
</div>


@*新建校区模态框*@
<div class="modal fade" id="createNewCapmus" tabindex="-1" role="dialog" aria-labelledby="createNewCapmusLabel"
     aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>新建校区</h3>
            </div>
@using (Html.BeginForm("CreateNewCampus", "BackGround", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
            <form role="form">
                <div class="modal-body">
                    <div class="box-content">
                        <div class="form-group">
                            @Html.Label("校区名称")
                            @Html.TextBoxFor(m => m.CampusName, new {@class = "form-control", @placeholder = "请输入校区名称"})  
                        </div>
                        <div class="form-group">
                            @Html.Label("校区编号")
                            @Html.TextBoxFor(m => m.CampusNumber, new {@class = "form-control", @placeholder = "请输入校区编号"})
                        </div>
                        <div class="form-group">
                            @Html.Label("校区简介")
                            @Html.TextBoxFor(m => m.CampusDescribe, new {@class = "form-control", @placeholder = "请输入校区简介"})
                        </div>
                        <div class="form-group">
                            @Html.Label("校区地址")
                            @Html.TextBoxFor(m => m.CampusAddress, new {@class = "form-control", @placeholder = "请输入校区地址"})
                        </div>
                    </div>
                </div>
                <div class="modal-footer form-group">
                    <a href="#" class="btn btn-default" data-dismiss="modal" >关闭</a>
                    <button type="submit" class="btn btn-primary">新建</button>
                </div>
            </form>
        </fieldset>
        }
</div>
    </div>
</div>


@*编辑校区模态框*@
<div class="modal fade" id="editCapmus" tabindex="-1" role="dialog" aria-labelledby="editCapmusLabel"
     aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>编辑校区信息</h3>
            </div>
            @using (Html.BeginForm("EditCampus", "BackGround", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <fieldset>
                    <form role="form">
                        <div class="modal-body">
                            <div class="box-content">
                                <div class="form-group">
                                    @Html.Label("校区ID")
                                    @Html.TextBoxFor(m => m.CampusId, new { @id = "cid", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    @Html.Label("校区名称")
                                    @Html.TextBoxFor(m => m.CampusName, new {@id = "cname", @class = "form-control", @placeholder = "请输入校区名称"})
                                </div>
                                <div class="form-group">
                                    @Html.Label("校区编号")
                                    @Html.TextBoxFor(m => m.CampusNumber, new {@id = "cnumber", @class = "form-control", @placeholder = "请输入校区编号"})
                                </div>
                                <div class="form-group">
                                    @Html.Label("校区简介")
                                    @Html.TextBoxFor(m => m.CampusDescribe, new {@id = "cdes", @class = "form-control", @placeholder = "请输入校区简介"})
                                </div>
                                <div class="form-group">
                                    @Html.Label("校区地址")
                                    @Html.TextBoxFor(m => m.CampusAddress, new {@id = "caddress", @class = "form-control", @placeholder = "请输入校区地址"})
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </form>
                </fieldset>
            }
        </div>
    </div>
</div>



<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well">
                <h2>
                    <i class="glyphicon glyphicon-info-sign"></i> 校区通知
                </h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default">
                        <i class="glyphicon glyphicon-cog"></i>
                    </a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>
                </div>
            </div>
            <div class="box-content row">
                <div class="col-lg-7 col-md-12">
                    <h1>
                        校区管理模块开发计划 <br>
                        <small>当前开发内容：新建校区功能以及多校区信息管理</small>
                    </h1>

                    <p class="center-block download-buttons">
                        <a href="#" class="btn btn-primary btn-lg" id="createNewCapmusBtn">
                            <i class="glyphicon glyphicon-briefcase glyphicon-white"></i> 新建校区
                        </a>
                    </p>
                </div>
           </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-briefcase"></i> 校区管理</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>校区名称</th>
                            <th>校区编号</th>
                            <th>校区简介</th>
                            <th>校区地址</th>
                            <th>修改操作</th>
                        </tr>
                    </thead>
                    <tbody>
                    @{
                        foreach (var c in campusInfos)
                        {
                            <tr>
                                <td>@c.Key</td>
                                <td class="center">@c.Value.CampusName</td>
                                <td class="center">@c.Value.CampusNumber</td>
                                <td class="center">@c.Value.CampusDescribe</td>
                                <td class="center">@c.Value.CampusAddress</td>
                                <td class="center">
                                    <a class="btn btn-success">
                                        <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                                        查看校区
                                    </a>
                                    <a class="btn btn-info" data-toggle="modal" data-target="#editCapmus" data-cid=@c.Value.CampusId data-cname=@c.Value.CampusName data-cnumber=@c.Value.CampusNumber data-cdes=@c.Value.CampusDescribe data-caddress=@c.Value.CampusAddress>
                                        <i class="glyphicon glyphicon-edit icon-white"></i>
                                        编辑
                                    </a>
                                    <a class="btn btn-danger" data-toggle="modal" data-target="#deleteCapmus" data-cid=@c.Value.CampusId data-cname=@c.Value.CampusName>
                                        <i class="glyphicon glyphicon-trash icon-white"></i>
                                        删除
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                        </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

OrangeManagementSystemMain/OrangeManagement/Views/BackGround/Login.cshtml
@{
    Session["LoginOrNot"] = true;
}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>橙果教育管理信息系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="橙果教育">

    <link id="bs-css" href="css/bootstrap-cerulean.min.css" rel="stylesheet">

    <link href="css/charisma-app.css" rel="stylesheet">
    <link href='bower_components/fullcalendar/dist/fullcalendar.css' rel='stylesheet'>
    <link href='bower_components/fullcalendar/dist/fullcalendar.print.css' rel='stylesheet' media='print'>
    <link href='bower_components/chosen/chosen.min.css' rel='stylesheet'>
    <link href='bower_components/colorbox/example3/colorbox.css' rel='stylesheet'>
    <link href='bower_components/responsive-tables/responsive-tables.css' rel='stylesheet'>
    <link href='bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css' rel='stylesheet'>
    <link href='css/jquery.noty.css' rel='stylesheet'>
    <link href='css/noty_theme_default.css' rel='stylesheet'>
    <link href='css/elfinder.min.css' rel='stylesheet'>
    <link href='css/elfinder.theme.css' rel='stylesheet'>
    <link href='css/jquery.iphone.toggle.css' rel='stylesheet'>
    <link href='css/uploadify.css' rel='stylesheet'>
    <link href='css/animate.min.css' rel='stylesheet'>

    <!-- jQuery -->
    <script src="bower_components/jquery/jquery.min.js"></script>


    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="img/favicon.ico">

</head>

<body>
    <div class="ch-container">
        <div class="row">

            <div class="row">
                <div class="col-md-12 center login-header">
                    <h2>橙果教育管理信息系统</h2>
                </div>
               
            </div>

            <div class="row">
                <div class="well col-md-5 center login-box">
                    <div class="alert alert-info">
                       请输入您的用户名和密码
                    </div>
                    <form class="form-horizontal" action="BackGround/BackGroundHome" method="post">
                        <fieldset>
                            <div class="input-group input-group-lg">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user red"></i></span>
                                <input type="text" class="form-control" placeholder="用户名">
                            </div>
                            <div class="clearfix"></div><br>

                            <div class="input-group input-group-lg">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock red"></i></span>
                                <input type="password" class="form-control" placeholder="密码">
                            </div>
                            <div class="clearfix"></div>


                            <div class="clearfix"></div>

                            <p class="center col-md-5">
                                <button type="submit" class="btn btn-primary">登陆</button>
                            </p>
                        </fieldset>
                    </form>
                </div>
            
            </div>
        </div>

    </div>

    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- 外部 javascript文件引入 -->

    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- cookie 管理类库 -->
    <script src="js/jquery.cookie.js"></script>
    <!-- 课程表 插件 -->
    <script src="bower_components/moment/min/moment.min.js"></script>
    <script src="bower_components/fullcalendar/dist/fullcalendar.js"></script>
    <!--数据表插件 -->
    <script src="js/jquery.dataTables.min.js"></script>
    <!-- 选择/下拉列表 -->
    <script src="bower_components/chosen/chosen.jquery.min.js"></script>
    <!-- 图像视觉插件 -->
    <script src="bower_components/colorbox/jquery.colorbox-min.js"></script>
    <!-- 通知插件 -->
    <script src="js/jquery.noty.js"></script>
    <!-- 制作表单响应 -->
    <script src="bower_components/responsive-tables/responsive-tables.js"></script>
    <!-- tour 插件 -->
    <script src="bower_components/bootstrap-tour/build/js/bootstrap-tour.min.js"></script>
    <!-- star rating 插件 -->
    <script src="js/jquery.raty.min.js"></script>
    <!-- IOS样式切换 -->
    <script src="js/jquery.iphone.toggle.js"></script>
    <!-- 自动伸缩文本插件 -->
    <script src="js/jquery.autogrow-textarea.js"></script>
    <!-- 多文件上传插件 -->
    <script src="js/jquery.uploadify-3.1.min.js"></script>
    <!-- history.js ajax调用跨浏览器状态改变 -->
    <script src="js/jquery.history.js"></script>
    <!-- mystyle -->
    <script src="js/charisma.js?@DateTime.Now.ToString("f")"></script>


</body>
</html>

OrangeManagementSystemMain/OrangeManagement/Views/Partials/Foot.cshtml
<footer class="row">
    <p class="col-md-9 col-sm-9 col-xs-12 copyright">
        &copy; <a href="#" target="_blank">
            Raymond
            Wang
        </a> 2015 - 2016
    </p>

    <p class="col-md-3 col-sm-3 col-xs-12 powered-by">
        <a href="#">橙果教育管理信息系统</a>
    </p>
</footer>

OrangeManagementSystemMain/OrangeManagement/Views/Partials/LeftMenu.cshtml
@using OrangeManagement.Models
@{
    var db = new DbHelper();
    
    var campusNameArray = db.CampusModule.ToArray();
}

<!-- leftmenu 部分 -->
<div class="col-sm-2 col-lg-2">
    <div class="sidebar-nav">
        <div class="nav-canvas">
            <div class="nav-sm nav nav-stacked">
            </div>
            <ul class="nav nav-pills nav-stacked main-menu">
                <li class="nav-header">最新信息</li>
                <li>
                    <a class="ajax-link" href="#"><i class="glyphicon glyphicon-home"></i><span> 通知版</span></a>
                </li>
                <li>
                    <a class="ajax-link" href="#"><i class="glyphicon glyphicon-eye-open"></i><span>企业新闻</span></a>
                </li>

                <li class="nav-header hidden-md">总部校区</li>

                <li class="accordion">
                    <a href="#"><i class="glyphicon glyphicon-plus"></i><span>分部校区信息</span></a>
                    <ul class="nav nav-pills nav-stacked">

                        @{
                            foreach (var i in campusNameArray)
                            {
                                var href = "CampusInfo?cname=" + i.CampusName;
                                
                                <li><a href=@href>@i.CampusName</a></li>
                            }
                        }                
                    </ul>
                </li>

                <li>
                    <a class="ajax-link" href="CampusManagement"><i class="glyphicon glyphicon-briefcase"></i><span>校区管理</span></a>
                </li>

                <li class="nav-header hidden-md">前台</li>
                <li>
                    <a class="ajax-link" href="#"><i class="glyphicon glyphicon-eye-open"></i><span>前台信息</span></a>
                </li>
                <li class="nav-header hidden-md">市场部</li>
                <li>
                    <a class="ajax-link" href="#"><i class="glyphicon glyphicon-eye-open"></i><span>市场信息</span></a>
                </li>
                <li class="nav-header hidden-md">营运部</li>
                <li>
                    <a class="ajax-link" href="#"><i class="glyphicon glyphicon-eye-open"></i><span>营运信息</span></a>
                </li>
                <li class="nav-header hidden-md">教务部</li>
                <li>
                    <a class="ajax-link" href="#"><i class="glyphicon glyphicon-eye-open"></i><span>教务信息</span></a>
                </li>
                <li class="nav-header hidden-md">人力资源部</li>
                <li>
                    <a class="ajax-link" href="#"><i class="glyphicon glyphicon-eye-open"></i><span>人力资源信息</span></a>
                </li>
                <li class="nav-header hidden-md">财务部</li>
                <li>
                    <a class="ajax-link" href="#"><i class="glyphicon glyphicon-eye-open"></i><span>财务信息</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- leftmenu 部分 -->

OrangeManagementSystemMain/OrangeManagement/Views/Partials/Topbar.cshtml
<!-- topbar 部分 -->
<div class="navbar navbar-default" role="navigation">

    <div class="navbar-inner">

        <button type="button" class="navbar-toggle pull-left animated flip">
            <span class="sr-only">管理导航</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>


        <a class="navbar-brand" href="#">
            <img alt="橙果教育 Logo" src="~/img/logo20.png" class="hidden-xs" />
            <span>橙果教育</span>
        </a>

        <!-- 用户列表菜单 -->
        <div class="btn-group pull-right">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-user"></i><span class="hidden-sm hidden-xs"> 管理员</span>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="#">个人信息</a></li>
                <li class="divider"></li>
                <li><a href="#">退出登录</a></li>
            </ul>
        </div>
        <!-- 用户列表菜单 -->


        <ul class="collapse navbar-collapse nav navbar-nav top-menu">
            <li><a href="#"><i class="glyphicon glyphicon-globe"></i> 官方首页</a></li>
            <li class="dropdown">
                <a href="#" data-toggle="dropdown">
                    <i class="glyphicon glyphicon-star"></i> 官方微信 <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">微信公众号</a></li>
                    <li><a href="#">微信关注人数统计</a></li>
                    <li><a href="#">微信新闻列表</a></li>
                    <li class="divider"></li>
                    <li><a href="#">微信流量分析</a></li>
                    <li class="divider"></li>
                    <li><a href="#">微信管理</a></li>
                </ul>
            </li>
        </ul>

    </div>
</div>
<!-- topbar 部分 -->